### ISSUE TITLE
IFAA stuff

### ISSUE THREAD

**Issue by mjtamlyn** [mjtamlyn/tamlynscore#104]
Spun out of #102 so I can merge the start of it

# TODO
- [x] *Priority* Flint round score sheet
- [x] *Priority* Updated batching code
- [x] *Need* Combined results mode (also use BySession but not ByRound)
- [x] *Need* Results should show score only (for both rounds) - just make sure I don't lose the column for Retired
- [x] *Need* A tie break field for ranking ties for 1st (details tbc) - this is basically the same CT/SO for cuts/rankings, so generically useful
- [ ] *Need* Team awards - Pre-nominated teams. 3 scores, plus a spare, total score across all 9 rounds. Teams are by bowstyle (but not gender or division), can have multiple teams. Do a hack where teams ending "Team" are the only teams which are teams.
- [x] _Pref_ Men/Women to Male/Female, and consistentise category names as "Adult Female Longbow" (e.g.)
- [x] _Pref_ Sponsor logos

**Comment by mjtamlyn** [comment]
Teams will be done by hand in the end cos it's a massive hack
